apiVersion: v1                # API version
kind: Service                 # Type of kubernetes resource 
metadata:
  name: redis    # Name of the resource
  labels:                     # Labels that will be applied to the resource
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:                  
    app: redis