apiVersion: v1                # API version
kind: Service                 # Type of kubernetes resource 
metadata:
  name: rabbitmq    # Name of the resource
  labels:                     # Labels that will be applied to the resource
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
  selector:                  
    app: rabbitmq