apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        visualize: "true"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12.2-management
        ports:
        - name: rabbitmq-server
          containerPort: 5672
        - name: rabbitmq-management
          containerPort: 15672