version: "3.7"

services:
  postgres:
    container_name: social-network-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  # api:
  #   container_name: social-network-api
  #   build:
  #     context: ../
  #     dockerfile: ./deploy/api/Dockerfile
  #   environment:
  #     - DB_DSN="postgres://postgres:123456@postgres/social-network?sslmode=disable"
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - postgres
  #   depends_on:
  #     - postgres
  
  redis:
    container_name: social-network-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - redis-network
    restart: unless-stopped

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
    ports:
    - "8081:8081"
    networks:
      - redis-network

  queue:
    container_name: rabbit-queue
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always

networks:
  postgres:
    driver: bridge
  redis-network:
    driver: bridge